Meter check
sensyn-robotics/mmpose pull request #2
Opened 2023-01-13 02:10 UTC by ahmedmustahid

## Motivation

## Modification

## BC-breaking (Optional)

## Use cases (Optional)

## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit tests to ensure correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-01-13 02:16 UTC, MasahiroOgawa commented
Please fill Motivation (or Objective) of this pull request.

2023-01-13 02:20 UTC, MasahiroOgawa commented
Please push data (and other binaries) separately.
e.g. push data into Google drive and write script to automatically download the dataset to specific directory.

2023-01-13 03:05 UTC, MasahiroOgawa requested changes

2023-01-13 03:05 UTC, MasahiroOgawa commented on coco_dataset_class_names.txt
> +{0: u'__background__',
Could you consider the place of this file to other child directory?
Because if you add this kind of files to the top directory, it becomes dirty.

2023-01-13 03:05 UTC, MasahiroOgawa commented on configs/_base_/datasets/meter.py
> +dataset_info = dict(
Is this proper place to put this data?
The directory name is under datasets/ so this should be placed other source code loaction.

2023-01-13 03:05 UTC, MasahiroOgawa commented on configs/_base_/datasets/meter.py
> +        dict(name='min', id=0, color=[51, 153, 255], type='', swap='max'),
Could you reme color to rgb_color or adding comment of the color order(e.g. RGB or BGR).

2023-01-13 03:05 UTC, MasahiroOgawa commented on configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py
> +#_base_ = [
Please delete this kind of unnecessary code.

2023-01-13 03:05 UTC, MasahiroOgawa commented on configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_meter_256x192.py
> +#_base_ = [
This lines too.

2023-01-13 03:05 UTC, MasahiroOgawa commented on configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_meter_256x192.py
> +        mean=[0.485, 0.456, 0.406],
Please add comment to this specific numbers (e.g. This comes from imagenet mean)

2023-01-13 03:05 UTC, MasahiroOgawa commented on configs/cocotiny/hrnet_w32_cocotiny_256x192.py
> +_base_="/home/ahmed/work/mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py"
You shouldn't add your local directory to the source code.

2023-01-13 03:05 UTC, MasahiroOgawa commented on configs/cocotiny/hrnet_w32_cocotiny_256x192.py
> +data_root = '/home/ahmed/work/mmpose/data/coco_tiny'
This one too.

2023-01-13 03:05 UTC, MasahiroOgawa commented on configs/cocotiny/hrnet_w32_cocotiny_256x192.py
> +data_root = '/home/ahmed/work/mmpose/data/coco_tiny'
same here.

2023-01-13 03:05 UTC, MasahiroOgawa commented on configs/meter/hrnetv2_w18_meter_256x256.py
> +_base_ = '/home/ahmed/work/mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_meter_256x192.py'
same here.

2023-01-13 03:05 UTC, MasahiroOgawa commented on configs/meter/hrnetv2_w18_meter_256x256.py
> +work_dir="/home/ahmed/work/mmpose/work_dirs/hrnet_w32_meter_256x192"
same

2023-01-13 03:05 UTC, MasahiroOgawa commented on configs/meter/hrnetv2_w18_meter_256x256.py
> +data_root = '/home/ahmed/work/coco-annotator'
same as above.

2023-01-13 03:05 UTC, MasahiroOgawa commented on demo/train_cocotiny.py
> +    "/home/ahmed/work/mmpose/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192.py"
same as above.

2023-01-13 03:05 UTC, MasahiroOgawa commented on demo/train_cocotiny.py
> +cfg.data_root = '/home/ahmed/work/mmpose/data/coco_tiny'
same as above.

2023-01-13 03:05 UTC, MasahiroOgawa commented on demo/webcam_cfg/meter_keypoint.py
> +            det_model_config="/home/ahmed/work/mmdetection/configs/yolox/yolox_tiny_8x8_300e_coco.py",
same as above.

2023-01-13 03:05 UTC, MasahiroOgawa commented on demo/webcam_cfg/meter_keypoint.py
> +            pose_model_checkpoint='/home/ahmed/work/mmpose/work_dirs/hrnet_w32_meter_256x192/latest.pth',
same as above.

2023-01-13 03:05 UTC, MasahiroOgawa commented on detection/detect_meter.py
> +root_dir="/home/ahmed/work/mmdetection/"
same as above.

2023-01-13 03:05 UTC, MasahiroOgawa commented on inference/infer_cocotiny.py
> +root_dir = "/home/ahmed/work/mmpose/"
same as above.

2023-01-13 03:05 UTC, MasahiroOgawa commented on inference/infer_meter.py
> +root_dir = "/home/ahmed/work/mmpose/"
same as above.

2023-01-13 03:05 UTC, MasahiroOgawa commented on log_meter.txt
> +load checkpoint from local path: /home/ahmed/work/mmpose/work_dirs/hrnet_w32_meter_256x192/latest.pth
Please ignore logs using .gitignore.

2023-01-13 03:05 UTC, MasahiroOgawa commented on mmpose/datasets/datasets/cocotiny/coco_tiny_dataset.py
> +import json
This file is also source code, so please consider to move this.

2023-01-13 03:05 UTC, MasahiroOgawa commented on requirements_tmp.txt
> +# This file may be used to create an environment using:
Why tmp?

2023-01-17 02:19 UTC, ahmedmustahid commented on configs/_base_/datasets/meter.py
> +dataset_info = dict(
> Is this proper place to put this data?
Yes this is the correct location. `_base_` is the directory that contains all the necessary features of a dataset.

2023-01-17 02:23 UTC, ahmedmustahid commented on configs/_base_/datasets/meter.py
> +        dict(name='min', id=0, color=[51, 153, 255], type='', swap='max'),
color is BGR. Will add a comment.

2023-01-17 02:42 UTC, ahmedmustahid commented on requirements_tmp.txt
> +# This file may be used to create an environment using:
not necessary. will remove this

2023-01-17 02:50 UTC, ahmedmustahid commented on configs/_base_/datasets/meter.py
> +        dict(name='min', id=0, color=[51, 153, 255], type='', swap='max'),
As a matter of fact, this is just for visualization. No particular restriction on the choice of pixel values.

2023-02-03 04:35 UTC, MasahiroOgawa commented
You still seems include image files though you add in .gitignore, probably because you add before adding those to .gitignore. So please reset or squash to delete image files.

2023-02-03 04:35 UTC, MasahiroOgawa requested changes
Sorry for my late review.

2023-02-03 04:35 UTC, MasahiroOgawa commented on configs/_base_/datasets/meter.py
> +dataset_info = dict(
I think e.g. "_base_/src" is more appropriate.

2023-02-03 04:35 UTC, MasahiroOgawa commented on configs/_base_/datasets/meter.py
> +        dict(name='min', id=0, color=[51, 153, 255], type='', swap='max'),
It's better to add color order comment for later implementation.

2023-02-07 04:31 UTC, merged